# This configuration file contains all options for the vulkan-renderer.
# Do not change any values unless you know exactly what you are doing!

title = "vulkan-renderer-configuration"

[application]
name = "Inexor-Application"

[application.engine]
name = "Inexor-Engine"

[application.window]
mode = "windowed"
width = 800
height = 800
name = "Inexor-Vulkan-Renderer"

# TODO: Use key/value pairs and give textures user friendly names.
[textures]
files = [
	"assets/textures/texture_A_1024.jpg",
	"assets/textures/texture_B_1024.jpg",
	"assets/textures/texture_C_1024.jpg",
	"assets/textures/texture_D_1024.jpg",
	"assets/textures/texture_E_1024.jpg",
	"assets/textures/texture_F_1024.jpg",
	"assets/textures/texture_G_1024.jpg",
	"assets/textures/logo_rendered.png",
]

[gltfmodels]
files = [
	"assets/models/inexor/inexor.gltf",
	"assets/models/inexor/5_objects.gltf"
]
